stages:
  - build
  - deploy

build-amd64-debian-stretch:
  stage: build
  image: debian:stretch
  script:
    - apt-get update && apt-get install -y debhelper
    - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch-backports.list
    - apt-get update && apt-get install -y -t stretch-backports debhelper quilt
    - rm /etc/apt/sources.list.d/stretch-backports.list
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_stretch/
    - mv ../*.deb built-packages/amd64/debian_stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_buster/
    - mv ../*.deb built-packages/amd64/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-stretch:
  stage: build
  image: multiarch/debian-debootstrap:armhf-stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_stretch/
    - mv ../*.deb built-packages/armhf/debian_stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-buster:
  stage: build
  image: multiarch/debian-debootstrap:armhf-buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_buster/
    - mv ../*.deb built-packages/armhf/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-xenial:
  stage: build
  image: ubuntu:xenial
  script:
    - apt-get update && apt-get install -y software-properties-common gcc cpp g++
    - add-apt-repository ppa:savoury1/build-tools
    - add-apt-repository ppa:savoury1/backports
    - apt-get update && apt-get install -y debhelper quilt ninja-build
    - rm /etc/apt/sources.list.d/savoury1-ubuntu-build-tools-xenial.list
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_xenial/
    - mv ../*.deb built-packages/amd64/ubuntu_xenial/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_bionic/
    - mv ../*.deb built-packages/amd64/ubuntu_bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-eoan:
  stage: build
  image: ubuntu:eoan
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_eoan/
    - mv ../*.deb built-packages/amd64/ubuntu_eoan/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

deploy-package:
  stage: deploy
  image: faucet/dbuilder
  script:
    - cd built-packages/
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet-test/debian/stretch amd64/debian_stretch/*.deb || true
    - package_cloud push faucetsdn/faucet-test/debian/buster amd64/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet-test/raspbian/stretch armhf/debian_stretch/*.deb || true
    - package_cloud push faucetsdn/faucet-test/raspbian/buster armhf/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet-test/ubuntu/xenial amd64/ubuntu_xenial/*.deb || true
    - package_cloud push faucetsdn/faucet-test/ubuntu/bionic amd64/ubuntu_bionic/*.deb || true
    - package_cloud push faucetsdn/faucet-test/ubuntu/eoan amd64/ubuntu_eoan/*.deb || true
